"""rem column phone number for user table

Revision ID: 1d59e1e3807f
Revises: 70bbad81816a
Create Date: 2025-02-01 17:49:21.210501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d59e1e3807f'
down_revision: Union[str, None] = '70bbad81816a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=33), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
